---
title: "Discussion on AI"
output: html_notebook
---


#8/31/23

In today's class we discussed an article on artificial intelligence. Throughout our discussion, a lot of points came up in favor of AI, but many included the fears and drawbacks of its potential. I learned a lot about AI from this discussion, but one thing I realized through the varying points being made is that AI can be a useful tool in the sciences if used ethically. Although we never came to a conclusion on "what is ethical," I think this could be a discussion worth having. And the definition of "what is ethical" will also change with time. So even if we proposed a definition in class, it may not stand in 6 months when new AI developments are made. 

If AI is used for simple tasks like coming up with summaries for existing literature, or explaining data in simpler terms, then I believe it can be a useful tool. Although, if it is used for writing manuscripts or grant applications then this is when it is being used unethically. Overall, I felt like we had a great discussion that got me thinking about the future of AI and I enjoyed hearing the multiple persepctives people had in class about this topic. 





