---
title: "Tools_7970"
output:
  html_document:
    df_print: paged
---


# 8/31/23

In today's class we discussed an article on artificial intelligence. Throughout our discussion, a lot of points came up in favor of AI, but many included the fears and drawbacks of its potential. I learned a lot about AI from this discussion, but one thing I realized through the varying points being made is that AI can be a useful tool in the sciences if used ethically. Although we never came to a conclusion on "what is ethical," I think this could be a discussion worth having. And the definition of "what is ethical" will also change with time. So even if we proposed a definition in class, it may not stand in 6 months when new AI developments are made. 

If AI is used for simple tasks like coming up with summaries for existing literature, or explaining data in simpler terms, then I believe it can be a useful tool. Although, if it is used for writing manuscripts or grant applications then this is when it is being used unethically. Overall, I felt like we had a great discussion that got me thinking about the future of AI and I enjoyed hearing the multiple perspectives people had in class about this topic. 

<span style="color:red">So true. Ethics themselves can be fluid and evolve along with the technology. I think the best thing we can be doing right now is talking about it. - Jonathon</span>

<mark> You can use three dashes as separator between your weekly reports, so the knitted document looks neat. Ani

---

# 9/6/23 discussion

This weeks class discussed a paper on creating equitable hiring strategies to move academic departments to a more diversified faculty. I led the discussion for this weeks paper and felt privileged to do so. I do have to admit, I felt a little uncomfortable as a white woman discussing how academic departments can increase diversity. But, I am thankful I was the one that had to do the work in making this weeks presentation and leading the discussion and it wasn't put on a student from a historically excluded group. Overall, I felt like the class was engaged in this weeks topic. I learned a lot from my classmates about things like requiring diversity statements and how students from underrepresented groups may feel exploited, or even tokenized, if they were to be required to write one. It was also interesting to hear how other countries don't have discussions about increasing diversity like we do in the U.S. I enjoyed hearing perspectives from everyone in the class and am happy we discussed this weeks topic as diversity in academia is lacking and we need to do better to increase it and make it feel more welcoming. 

<span style="color:red">I too can feel uncomfortable and uneducated when discussing DEI issues in academia. It's a challenging, but important topic, and you did a great job with the presentation. - Jonathon</span>

---

# 9/13/23 reproducibility crisis topic
In this weeks class we discussed a paper on how there are concerns in science with reproducing results. Honestly, before this class I was not aware of this big issue in the sciences. I've read papers that have had conflicting results to others, but had never heard of a "reproducibility crisis." I am thankful we discussed this topic because after hearing about it I agree this is going to become more of an issue over time as more studies on similar topics are conducted. Especially when practices like HARKing become integrated into common practices. I've worked with people that do this and I just thought it was normal practice, but I can see how it can be detrimental to reproducing the results found. Some of the other contributing factors to the reproducibility issue that we discussed in class was selective reporting, pressures to publish, and poor experimental design. We also discussed the big focus on p-values and how this can be detrimental because things like sample size can significantly change the results to be "significant." Overall, I enjoyed our discussion and am happy I am now aware of this issue so I can hopefully avoid it in future projects.

<span style="color:red">I'm so glad you feel like you learned something from this conversation! Honestly, I think the greater science community is only starting to get a handle on this, so welcome to the incipient party!  - Jonathon</span>



# 9/20/23 - bias in funding

This weeks topic was important to discuss because I feel like it occurs more often than we are aware and can cause bias in scientific results. The funding effect was defined as the idea or outcome of studies when either funded by private or public sponsors. We discussed how the funding effect is something that is real and causes reported results to be consistent with a sponsors interest. Things that happen include a failure to report results that dont benefit the sponsors. One example I found interested that Tristan mentioned in class was bias in spotted owl surveys in the west coast. Spotted oil surveys were conducted on land that was being scouted for timber harvesting and bias results were reporting saying the there were less owls in the areas where the forestry company wanted to harvest timber. This type of data manipulation and bias can be detrimental to the field of conservation and ecology since the results arent accurately reporting habitats the animals are inhabiting. And this bias seemed to happen due to the funding effect with the timber company. Im not sure how we address this issue since we as scientists need funding for our studies, and these private companies are good funding sources. Maybe we need like a checks and balances system to make sure good science and data reporting is being done. Another alternative could be to require studies to report their methods before being conducted, therefore all the results being collected must be reported. 

<span style="color:red">It's the reason lots of folks are pushing for pre-registering studies these days. That way, your methods and hypotheses are clearly articulated ahead of time, and the results are the results whether you like them or not. I honestly don't know where I stand on this idea because it sounds like a lot more work...  - Jonathon</span>


#9/27/23- citizen science
Oh, the topic of citizen science. I was actually quite surprised at the controversy that has come out of using citizen science as a data collection method from academics. I can understand the hesitancy as the data collected may not be the "best," but I think this misses one of the main goals of citizen science which is to get the public involved in the scientific process. As scientists we are all aware of the mistrust people have in science which boomed after COVID. I think one of the most beautiful things about citizen science is it connects folks with the scientific process showing them how important it can be. It also allows folks to connect with the natural environment around them. This can create an appreciation for the natural sciences resulting in the support of some of the bigger work being done in our fields. I think a lot of our discussion in class was focused around what we as scientists can get data wise by using citizen science. And although not all of the data can be used due to mistrust in how it was collected, I think the connection we make with non academic scientists is just as important as the data we "get" from their efforts. I do agree that not all citizen science data is usable, but it doesn't hurt to try! Yes, it can be time consuming. But the connections that can be made (as long as we have the time to do it) are worth it. 


#10/4 shiny app
I enjoyed seeing the process behind creating a shiny app. I was surprised that it wasn't too too complicated. Although I know we created a simple app and Im sure it gets more complex with additional elements added. I was given the task by Ani to use chat GPT to create mine and that was much easier than typing everything in! Chat GPT made an almost identical histogram to the one we created using Ani's code. Overall, it seems like you can do some cool stuff with shiny apps and Im happy we were introduced to it in this weeks class. 


#10/11 hypothesis testing in ecology 
Todays conversation got a little heated!! Just kidding, I think we had a great discussion on if hypotheses in ecology are necessary or if we can use other terminolgy in its place. What I took away from today's class is that developing sound and well thought through science is more crucial than if a study contains a so called "hypothesis." I agree with Jonathon that a hypothesis makes sure that we are thinking through the science, but I don't agree that "scientists are being lazy if they don't develop a hypothesis." I think that a lot of science has the idea of a hypothesis behind their work but it just isn't explicitly stated in their papers. I don't think its that scientists aren't capable of developing a hypothesis. Also, a good point that was mentioned in class is that the definition of what a hypothesis is can be unclear/changing from one person to another. If we are all taught different definitions of a hypothesis, then how can we determine if a study contains a proper hypothesis? I think hyperfocusing on "is there a hypothesis" is the wrong way to approach if a study is "good," and rather we should look at other aspects of the research and use that to determine if the results are useful. 




10/18/23 - Predatory journals
I learned a lot in todays class regarding predatory journals. Mainly that we don't have a good way to define them. I think a good start would be to define what a predatory journal is so we can better avoid them when going to publish. Some things we did discuss that could consider a journal predatory is inflated impact factors, easy/fast publishing, barely any peer review, and expensive rates for publishing. I was surprised that impact factors can be inflated in predatory journals. Although it makes sense if these journals commonly cite other papers within them since this increases the impact factor. I was shocked to hear that journals like Nature cost ~$9000 to publish in. How does this not put them in the category of predatory journals? That is a HUGE cost for a researcher or institution to pay. I think the best way we can combat predatory journals right now is by teaching grad students on how to look out for them. Once we know how to identify a predatory journal, we can hopefully avoid publishing them and potentially weed them out. 


10/25/23 - pre registration
Before our class I had never heard of preregsitering for a journal. When Jonathon first described it I though it was a great idea. You pre register your project, get it pre approved for being published in the journal, and you've got all your methods and data analysis sorted out before you even get the project sorted. Sounds ideal. Well after this weeks class, it didnt sound so ideal. The reality of pre registering includes potentially getting one set of reviewers that accepts your idea and says go ahead with the project. You complete the project, get a new set of reviewers, and they dont feel the same and say things should have been done differently. Then your paper gets denied. Based on this, it sounds like pre registering might be a waste of time. I hate to say that but if the goal is to know your work will get published no matter your results, but then it doesnt..seems like a lot of work with no benefit. I think in theory pre registering could be great because it prevents people from things like data hacking, publication biases towards significant results, and could cut down on publishing time. Based on where we're at with it right now, I will not be preregistering any of my work. Maybe in the future I will try it out!


